# Generated by Django 3.1.2 on 2020-10-31 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('kelas', models.CharField(max_length=200, null=True)),
                ('nim', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('semester', models.IntegerField()),
                ('sks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Assignment', 'Assignment'), ('Quiz', 'Quiz')], max_length=200, null=True)),
                ('status', models.CharField(choices=[('Unassigned', 'Unassigned'), ('Assigned', 'Assigned')], max_length=200, null=True)),
                ('deadline', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menolakforget.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menolakforget.subject')),
            ],
        ),
    ]
